### ISSUE TITLE
ArrayIndexOutOfBoundsException when using TRAVERSE in Java API

### ISSUE THREAD

**Issue by Skazzino** [orientechnologies/spark-orientdb#20] opened 2018-09-03 07:59 UTC
Hi,
I'm trying to use Spark Connector in Java to retrieve all nodes of a Tree using TRAVERSE.
This is my current code:
```Java
Map<String, String> propertiesBase = new TreeMap<>();
propertiesBase.put("user", "user");
propertiesBase.put("password", "pass");
propertiesBase.put("dburl", connectionString);
propertiesBase.put("vertextype", "VirtualTreeNode");
propertiesBase.put("spark", "true");

JavaRDD<Row> trees = sparkSession.read().format("org.apache.spark.orientdb.graphs").options(propertiesBase).option("query", query).load();
```

Everything is fine if I use a query like `SELECT * FROM (TRAVERSE OUT("E") FROM #30:568)`, where I put a specific VirtualTreeNode Root RID in the query.

If I use this one: `SELECT * FROM (TRAVERSE OUT("E") FROM (SELECT root_id FROM VirtualTreeMeta))` where `root_id` is the RID of the Tree Root saved in another Class (VirtualTreeMeta), the job crashes with this stack trace:
```
java.lang.ArrayIndexOutOfBoundsException: 0
	at org.apache.spark.sql.catalyst.expressions.GenericRow.get(rows.scala:173)
	at org.apache.spark.sql.Row$class.apply(Row.scala:163)
	at org.apache.spark.sql.catalyst.expressions.GenericRow.apply(rows.scala:165)
	at org.apache.spark.sql.execution.RDDConversions$$anonfun$rowToRowRdd$1$$anonfun$apply$3.apply(ExistingRDD.scala:60)
	at org.apache.spark.sql.execution.RDDConversions$$anonfun$rowToRowRdd$1$$anonfun$apply$3.apply(ExistingRDD.scala:57)
	at scala.collection.Iterator$$anon$11.next(Iterator.scala:409)
	at org.apache.spark.sql.catalyst.expressions.GeneratedClass$GeneratedIterator.processNext(Unknown Source)
	at org.apache.spark.sql.execution.BufferedRowIterator.hasNext(BufferedRowIterator.java:43)
	at org.apache.spark.sql.execution.WholeStageCodegenExec$$anonfun$8$$anon$1.hasNext(WholeStageCodegenExec.scala:377)
	at scala.collection.Iterator$$anon$11.hasNext(Iterator.scala:408)
	at scala.collection.Iterator$$anon$11.hasNext(Iterator.scala:408)
	at scala.collection.Iterator$class.foreach(Iterator.scala:893)
	at scala.collection.AbstractIterator.foreach(Iterator.scala:1336)
	at org.apache.spark.rdd.RDD$$anonfun$foreach$1$$anonfun$apply$28.apply(RDD.scala:917)
	at org.apache.spark.rdd.RDD$$anonfun$foreach$1$$anonfun$apply$28.apply(RDD.scala:917)
	at org.apache.spark.SparkContext$$anonfun$runJob$5.apply(SparkContext.scala:1944)
	at org.apache.spark.SparkContext$$anonfun$runJob$5.apply(SparkContext.scala:1944)
	at org.apache.spark.scheduler.ResultTask.runTask(ResultTask.scala:87)
	at org.apache.spark.scheduler.Task.run(Task.scala:99)
	at org.apache.spark.executor.Executor$TaskRunner.run(Executor.scala:282)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624)
	at java.lang.Thread.run(Thread.java:748)
```
I've also tried to force the schema of the table in this way: 
```Java
StructType schema = sparkSession.read().format("org.apache.spark.orientdb.graphs").options(propertiesBase).option("query", "SELECT * FROM VirtualTreeNode LIMIT 1").load().schema();

JavaRDD<Row> trees =   /* same above */.schema(schema).load();
```
But same Exception.
Am I doing something wrong? Can you help me please? Thanks.

**Comment by luigidellaquila** [comment] 2018-09-03 08:35
Hi @Skazzino 

Any chance to have a small test case to reproduce the problem?

Thanks

Luigi

**Comment by Skazzino** [comment] 2018-09-03 09:51
Here's the Unit Test:
```Java
package test;

import static org.junit.Assert.*;

import java.util.Map;
import java.util.TreeMap;

import org.apache.spark.api.java.JavaSparkContext;
import org.apache.spark.sql.Dataset;
import org.apache.spark.sql.Row;
import org.apache.spark.sql.SparkSession;
import org.apache.spark.sql.types.StructType;
import org.junit.Test;

public class TestOrient {

	@Test
	public void test() {
		JavaSparkContext session = new JavaSparkContext(
				"local[8]", 
				"TEST"
		);
		
		SparkSession sparkSession = SparkSession.builder().sparkContext(session.sc()).getOrCreate();
 		
 		Map<String, String> propertiesBase = new TreeMap<>();
		propertiesBase.put("user", "INSERT_USER");
		propertiesBase.put("password", "INSERT_PASS");
		propertiesBase.put("dburl", "remote:localhost:2424/INSERT_DB");
		propertiesBase.put("vertextype", "VirtualTreeNode");
		propertiesBase.put("spark", "true");
		
		StructType schema = sparkSession.read()
									    .format("org.apache.spark.orientdb.graphs")
									    .options(propertiesBase)	
									    .option("query", "SELECT * FROM VirtualTreeNode LIMIT 1")
									    .load()
									    .schema();
		
 		Dataset<Row> treesOk = sparkSession.read()
											 .format("org.apache.spark.orientdb.graphs")
											 .options(propertiesBase)
											 .option("query", "SELECT * FROM (TRAVERSE OUT(\"E\") FROM #27:0)")
											 .schema(schema)
											 .load();
		
 		Dataset<Row> treesError = sparkSession.read()
											 .format("org.apache.spark.orientdb.graphs")
											 .options(propertiesBase)
											 .option("query", "SELECT * FROM (TRAVERSE OUT(\"E\") FROM (SELECT root_id FROM VirtualTreeMeta))")
											 .schema(schema)
											 .load();
 		
 		/* Works */
 		assertEquals(treesOk.count(), 6);
 		
 		/* Doesn't work */
 		assertEquals(treesError.count(), 6);
 		
 		session.close();
	}

}
```
Here's our db to run it:
[trees-repo(1).gz](https://github.com/orientechnologies/spark-orientdb/files/2345071/trees-repo.1.gz)

**Comment by Skazzino** [comment] 2018-09-03 14:44
It seems like only the first subquery is executed (`SELECT root_id FROM VirtualTreeMeta`), the `TRAVERSE` and the outer query are ignored, in fact the `count` returned is equals to the number of records in this class. So I think the exception is triggered because it tries to parse the VirtualTreeMeta schema but it has the VirtualTreeNode one loaded.

**Comment by Skazzino** [comment] 2018-09-06 15:10
@luigidellaquila any news on this issue?

**Comment by Skazzino** [comment] 2018-09-18 08:57
@luigidellaquila Still waiting for a feedback. My project will really benefit of this fix since I've to collect the rids from Spark and use them to build an adhoc query...

**Comment by luigidellaquila** [comment] 2018-09-18 09:03
hi @Skazzino 

Sorry for the late reply, I'm checking it now.
Just to have the complete picture, which exact OrientDB version are you using?

Thanks

Luigi

**Comment by Skazzino** [comment] 2018-09-18 09:09
I'm using:
- OrientDB version: 3.0.6
- Spark version: 2.1.0
- Orient-Spark Connector:
  - ArtifactId: spark-orientdb-2.2.1_2.11
  - Version: 1.4

Sorry for the previous spam :D!

**Comment by luigidellaquila** [comment] 2018-09-18 09:54
Hi @Skazzino 

I'm having a bit of trouble reproducing the problem. Do you have a chance to attach a full Maven (or whatever) project with the complete configuration of dependencies? Sorry for the round trip...

Thanks

Luigi

**Comment by Skazzino** [comment] 2018-09-18 10:11
I'm attaching the pom.xml dependencies:

```xml
<project xmlns="http://maven.apache.org/POM/4.0.0" xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
	xsi:schemaLocation="http://maven.apache.org/POM/4.0.0 http://maven.apache.org/xsd/maven-4.0.0.xsd">
	<modelVersion>4.0.0</modelVersion>
	<groupId>Test Orient</groupId>
	<artifactId>Test Orient</artifactId>
	<version>0.0.1-SNAPSHOT</version>
	
<dependencies>
		<dependency>
			<groupId>com.orientechnologies</groupId>
			<artifactId>orientdb-client</artifactId>
			<version>3.0.6</version>
		</dependency>

		<dependency>
			<groupId>org.apache.spark</groupId>
			<artifactId>spark-catalyst_2.11</artifactId>
			<version>2.1.0</version>
		</dependency>

		<dependency>
			<groupId>org.apache.spark</groupId>
			<artifactId>spark-core_2.11</artifactId>
			<version>2.1.0</version>
		</dependency>
		
		<dependency>
    		<groupId>com.orientechnologies</groupId>
    		<artifactId>orientdb-graphdb</artifactId>
    		<version>3.0.6</version>
		</dependency>
				
		<dependency>
   			<groupId>org.apache.spark</groupId>
   			<artifactId>spark-orientdb-2.2.1_2.11</artifactId>
   			<version>1.4</version>
		</dependency>
		
		<dependency>
    		<groupId>com.orientechnologies</groupId>
    		<artifactId>orientdb-jdbc</artifactId>
    		<version>3.0.6</version>
		</dependency>
	</dependencies>

	<repositories>
		<repository>
			<id>bintray</id>
			<name>bintray</name>
			<url>https://dl.bintray.com/sbcd90/org.apache.spark/</url>
		</repository>
	</repositories>
</project>
```

I left only the orientdb + Spark dependencies we're using. Thanks again for your help!

**Comment by luigidellaquila** [comment] 2018-09-18 10:18
Fantastic, thank you very much!

Luigi

**Comment by luigidellaquila** [comment] 2018-09-18 10:38
Hi @Skazzino 

I think I found the problem. If you try the following, it will work fine:

```
SELECT * FROM (TRAVERSE OUT("E") FROM (SELECT expand(root_id) FROM VirtualTreeMeta))
```

(see the `expand(root_id)`)

The Spark connector still uses the legacy SQL executor, this is why your query works in Studio (that uses the new executor)  but not in the application.

I'll schedule an upgrade of the driver to support the new executor, but I think it will take a while...

Thanks

Luigi

**Comment by Skazzino** [comment] 2018-09-18 12:35
@luigidellaquila It works, grazie mille! :D 

By the way, this query is really slow with the spark connector, but really fast in Studio. It takes 18s to read a 128 records chunk. 

Since I'm reading data chunks from OrientDB (my db is like 4M of records) to Spark, what I ask you is: is there any way to keep the OrientDB connection opened while loading DataFrames?

My actual code is:
```Java
SparkSession sparkSession = SparkSession.builder()
								.sparkContext(jsc.sc())
								.getOrCreate();
/* Properties stuff */
String query = "...";
 
JavaRDD<Row> trees = sparkSession.read()
							.format("org.apache.spark.orientdb.graphs")
							.options(propertiesBase)
							.option("query", query)
						        .schema(schema)
							.load()
							.toJavaRDD();
```

And this method is called for every chunk. So I wonder if there's some way to keep the connection alive.
Thanks in advance!

**Comment by luigidellaquila** [comment] 2018-09-18 12:37
Hi @Skazzino 

I think it is due to the usage of the legacy API, there is a chance that it will be fixed with the enhancement. 
Unfortunately, as of now there is no option to keep the session open. The DB is pooled already, so maybe we can further optimize it. I'll see if we can add it in the future

Thanks

Luigi

**Comment by Skazzino** [comment] 2018-09-18 12:53
Great! Hope to get enhancement soon! :D

Thank you really much!

**Closed** 2020-12-02 11:50 UTC
Labels: enhancement
